with open("pages/admin_dashboard.py", "r", encoding="utf-8") as f:
    lines = f.readlines()

new_lines = lines[:73]
new_lines.append("if role_id == 3:\n")
for line in lines[73:]:
    if line.strip() == "":
        new_lines.append("\n")
    else:
        new_lines.append("    " + line)

new_lines.extend([
    "\n",
    "elif role_id == 1:\n",
    "    st.header(\"Panel Operativo - Cajero\")\n",
    "    st.info(\"Buscador de Cuentas y Procesamiento de Transacciones rápidos.\")\n",
    "    \n",
    "    # Buscador de cuenta visual para el cajero\n",
    "    from models.account_model import get_account_by_number\n",
    "    from services.transaction_service import create_simple_transaction\n",
    "    \n",
    "    search_acc = st.text_input(\"🔍 Buscar Cuenta por Número (Ej. SV_synapse...)\")\n",
    "    if search_acc:\n",
    "        acc_data = get_account_by_number(search_acc)\n",
    "        if acc_data:\n",
    "            acc_id = acc_data[0] if isinstance(acc_data, (list, tuple)) else acc_data.get('Id_account')\n",
    "            st.success(f\"Cuenta encontrada: ID {acc_id}\")\n",
    "            with st.form(\"cajero_tx_form\"):\n",
    "                tx_type = st.selectbox(\"Tipo de Operación\", [\"Depósito\", \"Retiro\"])\n",
    "                tx_amount = st.number_input(\"Monto\", min_value=0.01, step=10.0)\n",
    "                tx_desc = st.text_input(\"Descripción\")\n",
    "                st.markdown('<div class=\"btn-success\">', unsafe_allow_html=True)\n",
    "                sub_tx = st.form_submit_button(\"Procesar Operación\", type=\"primary\")\n",
    "                st.markdown('</div>', unsafe_allow_html=True)\n",
    "                if sub_tx:\n",
    "                    if not tx_desc or tx_amount <= 0:\n",
    "                        st.warning(\"Complete todos los campos de la operación.\")\n",
    "                    else:\n",
    "                        # 2 Retiro (Debit) / 3 Depósito (Credit)\n",
    "                        t_id = 2 if tx_type == \"Retiro\" else 3\n",
    "                        entry = \"debit\" if t_id == 2 else \"credit\"\n",
    "                        res = create_simple_transaction(\n",
    "                            account_id=acc_id,\n",
    "                            amount=tx_amount,\n",
    "                            entry_type=entry,\n",
    "                            description=tx_desc,\n",
    "                            created_by_user_id=st.session_state['user_data']['Id_user'],\n",
    "                            transaction_type_id=t_id\n",
    "                        )\n",
    "                        if res.get('success'):\n",
    "                            msg = res.get('message', 'Operación ejecutada con éxito.')\n",
    "                            st.success(msg)\n",
    "                        else:\n",
    "                            st.error(res.get('error'))\n",
    "        else:\n",
    "            st.error(\"Cuenta no encontrada.\")\n",
    "\n",
    "elif role_id == 4:\n",
    "    st.header(\"Panel de Métricas - Analista Financiero\")\n",
    "    st.write(\"Vista de solo lectura (Resumen global).\")\n",
    "    from services.rbac_service import execute_analyst_query\n",
    "    res = execute_analyst_query()\n",
    "    if res.get('status') == 200:\n",
    "        data = res['data']\n",
    "        import pandas as pd\n",
    "        col_a1, col_a2 = st.columns(2)\n",
    "        with col_a1:\n",
    "            st.subheader(\"Flujo de Caja Global\")\n",
    "            if data['flujo']:\n",
    "                df_flujo = pd.DataFrame(data['flujo'])\n",
    "                st.bar_chart(df_flujo, x='entry_type', y='total', color='#10B981')\n",
    "            else:\n",
    "                st.info('Sin datos en contabilidad.')\n",
    "        with col_a2:\n",
    "            st.subheader(\"Volumen de Transacciones\")\n",
    "            if data['tipos']:\n",
    "                df_tipos = pd.DataFrame(data['tipos'])\n",
    "                st.bar_chart(df_tipos, x='name', y='count', color='#3B82F6')\n",
    "            else:\n",
    "                st.info('Sin datos por tipo.')\n",
    "        \n",
    "        st.divider()\n",
    "        st.subheader(\"Detalle de Volúmenes por Tipo\")\n",
    "        if data['tipos']:\n",
    "            st.dataframe(df_tipos, use_container_width=True)\n",
    "    else:\n",
    "        st.error(res.get('error'))\n",
    "\n",
    "elif role_id == 5:\n",
    "    st.header(\"Control de Riesgos - Auditor\")\n",
    "    st.write(\"Historial Detallado de Operaciones del Sistema. (Solo Lectura)\")\n",
    "    from services.rbac_service import execute_auditor_query\n",
    "    res = execute_auditor_query()\n",
    "    if res.get('status') == 200:\n",
    "        history = res['data']\n",
    "        if history:\n",
    "            import pandas as pd\n",
    "            df = pd.DataFrame(history)\n",
    "            \n",
    "            c_f1, c_f2 = st.columns([1, 2])\n",
    "            with c_f1:\n",
    "                filter_user = st.text_input('🔍 Filtrar historial por \"created_by\" (Usuario/Email)')\n",
    "            \n",
    "            if filter_user:\n",
    "                df = df[df['created_by'].astype(str).str.contains(filter_user, case=False, na=False)]\n",
    "                \n",
    "            st.dataframe(df, use_container_width=True)\n",
    "        else:\n",
    "            st.info('El libro mayor está vacío.')\n",
    "    else:\n",
    "        st.error(res.get('error'))\n"
])

with open("pages/admin_dashboard.py", "w", encoding="utf-8") as f:
    f.writelines(new_lines)
